[package]
name = "vote-service"
version = "0.1.0"
authors = ["Jonh Doe <kormick@rambler.ru>"]

[dependencies]
exonum = { version = "0.9.0", path = "../../exonum/exonum" }
failure = "0.1.2"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"